version: '3'
services:
    # PostgreSQL database service
  database:
    image: postgres:15
    # Map postgres usual port to same port on host
    ports:
      - "5432:5432"
    # DB environment variables
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gateways-user
    # Defining volumes
    volumes:
      - db_data:/var/lib/postgresql     # Volume to persist db data
      - ./src/database:/docker-entrypoint-initdb.d   # Volume link to local SQL scripts which creates DBs
  
  # Java springboot api service 
  gateways-user:
    build:
      # Dockerfile context with build steps and .jar output
      context: .
      dockerfile: Dockerfile
    # Map application localhost port to host port
    ports:
      - 9038:8000

volumes:
  db_data: